const items = $input.all();

if (!items || items.length === 0) {
  return [{ json: { html: '<p>No changes detected.</p>', subject: 'Catalogue Update: No Changes' } }];
}

const newProducts  = items.filter(i => i.json.change_type === 'NEW');
const priceChanges = items.filter(i => i.json.change_type === 'PRICE_CHANGE');
const tagChanges   = items.filter(i => i.json.change_type === 'TAG_CHANGE');
const removedItems = items.filter(i => i.json.change_type === 'REMOVED');

function buildRow(item) {
  const d = item.json;
  let priceCell = '';
  if (d.old_price && d.old_price !== d.price) {
    priceCell = '<s style="color:#999">Rs.' + d.old_price + '</s> &rarr; <b>Rs.' + d.price + '</b>';
  } else {
    priceCell = 'Rs.' + (d.price || '-');
  }
  let tagCell = '';
  if (d.old_tags && d.old_tags !== d.tags) {
    tagCell = '<span style="color:#999">[was: ' + d.old_tags + ']</span> &rarr; ' + (d.tags || '-');
  } else {
    tagCell = d.tags || '-';
  }
  return '<tr>'
    + '<td style="padding:8px;border:1px solid #ddd">' + (d.name || '-') + '</td>'
    + '<td style="padding:8px;border:1px solid #ddd">' + (d.category || '-') + '</td>'
    + '<td style="padding:8px;border:1px solid #ddd">' + priceCell + '</td>'
    + '<td style="padding:8px;border:1px solid #ddd">' + tagCell + '</td>'
    + '</tr>';
}

function buildSection(title, color, list) {
  if (!list.length) return '';
  let rows = '';
  for (let i = 0; i < list.length; i++) { rows += buildRow(list[i]); }
  return '<h3 style="font-family:sans-serif;color:' + color + ';margin-top:24px">' + title + ' (' + list.length + ')</h3>'
    + '<table style="border-collapse:collapse;width:100%;font-family:sans-serif;font-size:13px">'
    + '<tr style="background:#f0f0f0">'
    + '<th style="padding:8px;border:1px solid #ddd;text-align:left">Product</th>'
    + '<th style="padding:8px;border:1px solid #ddd;text-align:left">Category</th>'
    + '<th style="padding:8px;border:1px solid #ddd;text-align:left">Price</th>'
    + '<th style="padding:8px;border:1px solid #ddd;text-align:left">Tags</th>'
    + '</tr>'
    + rows
    + '</table>';
}

const brand    = items[0].json.brand || 'Competitor';
const runDate  = new Date().toLocaleDateString('en-IN', { dateStyle: 'full' });
const total    = items.length;

let html = '<div style="font-family:sans-serif;max-width:700px;margin:auto">';
html += '<h2 style="color:#1a1a1a">Catalogue Intelligence: ' + brand + '</h2>';
html += '<p style="color:#555">Run date: ' + runDate + ' &nbsp;|&nbsp; <b>' + total + ' changes detected</b></p>';

html += '<table style="border-collapse:collapse;width:100%;font-size:13px;margin-bottom:16px">';
html += '<tr style="background:#f7f7f7">'
  + '<th style="padding:8px;border:1px solid #ddd">New Products</th>'
  + '<th style="padding:8px;border:1px solid #ddd">Price Changes</th>'
  + '<th style="padding:8px;border:1px solid #ddd">Tag Changes</th>'
  + '<th style="padding:8px;border:1px solid #ddd">Removed</th>'
  + '</tr>';
html += '<tr style="text-align:center;font-weight:bold">'
  + '<td style="padding:8px;border:1px solid #ddd;color:#2e7d32">' + newProducts.length + '</td>'
  + '<td style="padding:8px;border:1px solid #ddd;color:#e65100">' + priceChanges.length + '</td>'
  + '<td style="padding:8px;border:1px solid #ddd;color:#1565c0">' + tagChanges.length + '</td>'
  + '<td style="padding:8px;border:1px solid #ddd;color:#b71c1c">' + removedItems.length + '</td>'
  + '</tr>';
html += '</table>';

html += buildSection('NEW Products', '#2e7d32', newProducts);
html += buildSection('Price Changes', '#e65100', priceChanges);
html += buildSection('Tag Changes', '#1565c0', tagChanges);
html += buildSection('Removed Products', '#b71c1c', removedItems);

html += '<p style="color:#aaa;font-size:11px;margin-top:32px">Auto-generated by Catalogue Monitor &middot; ' + runDate + '</p>';
html += '</div>';

const subject = 'Catalogue Update: ' + total + ' changes | ' + brand + ' | ' + runDate;

return [{
  json: {
    html: html,
    subject: subject,
    change_count: total,
    new_count: newProducts.length,
    price_change_count: priceChanges.length,
    tag_change_count: tagChanges.length,
    removed_count: removedItems.length
  }
}];